In [92]:
import pandas as pd 
import numpy as np

# Wages ([Statistics Canada - Wages from 2012 to 2024](https://open.canada.ca/data/en/dataset/adad580f-76b0-4502-bd05-20c125de9116))

In [93]:
# Load all wages datasets
df_2012 = pd.read_csv("../datasets/wages/2012 Wages.csv")
df_2013 = pd.read_csv("../datasets/wages/2013 Wages.csv")
df_2014 = pd.read_csv("../datasets/wages/2014 Wages.csv")
df_2015 = pd.read_csv("../datasets/wages/2015 Wages.csv")
df_2016 = pd.read_csv("../datasets/wages/2016 Wages.csv")

df_2019 = pd.read_csv("../datasets/wages/2019 Wages.csv")
df_2020 = pd.read_csv("../datasets/wages/2020 Wages.csv")
df_2021 = pd.read_csv("../datasets/wages/2021 Wages.csv")
df_2022 = pd.read_csv("../datasets/wages/2022 Wages.csv")
df_2023 = pd.read_csv("../datasets/wages/2023 Wages.csv", low_memory=False)
df_2024 = pd.read_csv("../datasets/wages/2024 Wages.csv")

# These 2 datasets have a different encoding
df_2017 = pd.read_csv("../datasets/wages/2017 Wages.csv", encoding='iso-8859-1') 
df_2018 = pd.read_csv("../datasets/wages/2018 Wages.csv", encoding='iso-8859-1')

## **Transformation**

#### **Combine all Wages datasets** 

We are dealing with 13 annual wage datasets (2012–2024).  
To enable efficient analysis and cross-year comparison, we must first standardize the column names and then combine them into a single unified DataFrame.

In [94]:
# Create list of dataframes with their corresponding years
dataframes = [
    (df_2012, 2012),
    (df_2013, 2013),
    (df_2014, 2014),
    (df_2015, 2015),
    (df_2016, 2016),
    (df_2017, 2017),
    (df_2018, 2018),
    (df_2019, 2019),
    (df_2020, 2020),
    (df_2021, 2021),
    (df_2022, 2022),
    (df_2023, 2023),
    (df_2024, 2024)
]

Check all present column names.

In [95]:
# Aggregate all unique column names from the 13 datasets
all_unique_columns = set()

# Iterate through the list of (dataframe, year) tuples
for df, year in dataframes:
    # Add all columns from the current DataFrame to the set
    all_unique_columns.update(df.columns.tolist())

# Convert the set back to a sorted list for clear display
sorted_unique_columns = sorted(list(all_unique_columns))

print("Total unique column names across all wage datasets:")
print(f"Count: {len(sorted_unique_columns)}")
print("-" * 50)
for col in sorted_unique_columns:
    print(col)

Total unique column names across all wage datasets:
Count: 49
--------------------------------------------------
Annual Wage Flag_Salaire annuel
Annual_Wage
Annual_Wage_Flag_Salaire_annuel
Average_Wage_Salaire_Moyen
Commentaire_Salaire
Data Source
Data_Source_E
Data_Source_F
ER Code_Code RE
ER Name_Nom RE
ER_Code
ER_Code_Code_RE
ER_Name
ER_Name_Nom_RE
Economic_Region
High Wage_Salaire maximal
High_Wage_Salaire_Maximal
Low Wage_Salaire Minium
Low_Wage_Salaire_Minium
Median wage_Salaire Median
Median_Wage_Salaire_Median
NOC Title
NOC_CNP
NOC_CNP_2006
NOC_TITLE_ENG
NOC_TITLE_FRA
NOC_Title
NOC_Title_E
NOC_Title_F
NOC_Title_eng
NOC_Title_fra
Nom_RE
Non_WageBen_pct
PROV
Prov
Quartile1_Wage_Salaire_Quartile1
Quartile3_Wage_Salaire_Quartile3
Reference Period_Periode de reference
Reference_Period
Revision Date_Date revision
Revision_Date_Date_revision
Source de donnees
Titre CNP
Titre_CNP
Wage_Comment
Wage_Comment_E
Wage_Comment_F
Wage_Comment_F1
prov

Finding **49 unique column names** across the 13 input files immediately highlights the major issue of inconsistent formatting.

In [96]:
# The column mappings (all lower-case)

# The column rename/standardization mapping
RENAME_MAP = {
    # NOC code
    'noc_cnp_2006': 'noc_code',
    'noc_cnp': 'noc_code',
    # NOC title
    'noc_title_e': 'noc_title',
    'noc_title_eng': 'noc_title',
    # Economic region info
    'er_name_nom_re': 'er_name',
    'economic_region': 'er_name',
    'er_code_code_re': 'er_code',
    # Wage info
    'low_wage_salaire_minium': 'low_wage',
    'high_wage_salaire_maximal': 'high_wage',
    'median_wage_salaire_median': 'median_wage',
    'annual_wage_flag_salaire_annuel': 'annual_flag',
    'annual_wage': 'annual_flag',
    'wage_comment_e': 'wage_comment',
}

# French language columns to drop
FRENCH_COLUMNS_TO_DROP = [
    'nom_re',
    'titre_cnp',
    'noc_title_f',
    'noc_title_fra',
    'noc_title_french',
    'data_source_f',
    'source_de_donnees',
    'wage_comment_f',
    'wage_comment_f1',
    'commentaire_salaire',
]

# Other columns to drop
OTHER_COLUMNS_TO_DROP = [
    'non_wageben_pct',
    'reference_period',
    'revision_date',
    'revision_date_date_revision',
    'reference_period_periode_de_reference',
    'revision_date_date_revision',
    'data_source_e',
    'data_source',
    'prov',
    'average_wage_salaire_moyen',
    'quartile1_wage_salaire_quartile1',
    'quartile3_wage_salaire_quartile3',
]

# Process each dataframe

standard_col_dfs = []

for df, year in dataframes:
    df = df.copy()
    
    # Add year as the first column
    df['year'] = year
    df = df[['year'] + [col for col in df.columns if col != 'year']]
    
    # Standardize all column names casing
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

    # Drop French columns
    cols_to_drop = [col for col in FRENCH_COLUMNS_TO_DROP if col in df.columns]
    if cols_to_drop:
        df.drop(columns=cols_to_drop, inplace=True)
    
    # Drop other unwanted columns
    cols_to_drop = [col for col in OTHER_COLUMNS_TO_DROP if col in df.columns]
    if cols_to_drop:
        df.drop(columns=cols_to_drop, inplace=True)
    # in 2016, there is an empty 'Annual_Wage_Flag_Salaire_annuel' column
    if year == 2016:
        df.drop(columns='annual_wage_flag_salaire_annuel', inplace=True)
    
    # Rename the columns to adhere to the single naming standard
    for old_col, new_col in RENAME_MAP.items():
        if old_col in df.columns:
            df.rename(columns={old_col: new_col}, inplace=True)

    print(f"{year} - Final columns: {df.columns.tolist()}")
    standard_col_dfs.append(df)


# Combine all dataframes
wages_df = pd.concat(standard_col_dfs, ignore_index=True)


print("\nCOMBINED DATAFRAME INFO")
print("="*80)
print(f"Dimensions: {wages_df.shape}")
wages_df.head()

2012 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2013 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2014 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2015 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2016 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'wage_comment', 'annual_flag']
2017 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2018 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2019 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2020 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2021 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2022 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2023 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']
2024 - Final columns: ['year', 'noc_code', 'noc_title', 'er_code', 'er_name', 'low_wage', 'median_wage', 'high_wage', 'annual_flag', 'wage_comment']

COMBINED DATAFRAME INFO
================================================================================
Dimensions: (568632, 10)

,year,noc_code,noc_title,er_code,er_name,low_wage,median_wage,high_wage,annual_flag,wage_comment
0,2012,11,Legislators,ER00,National,8.17,28.00,49.45,0,NaN
1,2012,11,Legislators,ER10,Newfoundland and Labrador,17.95,40.06,64.97,0,NaN
2,2012,11,Legislators,ER1010,Avalon Peninsula,19.23,45.67,66.67,0,NaN
3,2012,11,Legislators,ER1020,South Coast--Burin Peninsula,NaN,NaN,NaN,0,"Due to data limitations, the wage for this occ..."
4,2012,11,Legislators,ER1030,West Coast--Northern Peninsula--Labrador,NaN,NaN,NaN,0,"Due to data limitations, the wage for this occ..."

We can see that the dataset standardization and merging were successful.

#### **Narrow the scope**

To align with the scope of our national-level AI impact analysis, we will focus on the country-level data.

In [97]:
# We'll focus on national-level data to match the AI adoption scope
# Canada = Economic Region - 'ER00'
wages_df = wages_df[wages_df['er_code'] == 'ER00'].copy()

print(wages_df.head().to_string())

# Check the Economic Region name consistency
print(f'\n {wages_df['er_name'].unique()}')

     year noc_code                                                                                        noc_title er_code   er_name  low_wage  median_wage  high_wage  annual_flag wage_comment
0    2012       11                                                                                      Legislators    ER00  National      8.17        28.00      49.45            0          NaN
86   2012       12                                                         Senior Government Managers and Officials    ER00  National     20.64        46.15      74.36            0          NaN
172  2012       13                          Senior Managers - Financial, Communications and Other Business Services    ER00  National     20.29        40.87      75.83            0          NaN
258  2012       14  Senior Managers - Health, Education, Social and Community Services and Membership Organizations    ER00  National     19.23        38.46      66.67            0          NaN
344  2012       15                                 Senior Managers - Trade, Broadcasting and Other Services, n.c.a.    ER00  National     18.90        40.87      72.12            0          NaN

 ['National' 'Canada']

In [98]:
# Replace all instances of 'National' with 'Canada' in the 'er_name' column
wages_df['er_name'] = wages_df['er_name'].replace('National', 'Canada')

print('The wages_df dimensions:', wages_df.shape)
print('\n', wages_df.groupby('year').size())

The wages_df dimensions: (6612, 10)

 year
2012    520
2013    520
2014    520
2015    520
2016    500
2017    500
2018    500
2019    500
2020    500
2021    500
2022    500
2023    516
2024    516
dtype: int64

With the scope narrowed, the final DataFrame contains 500 to 520 corresponding occupation records for each year of the analysis.

#### **Check the annual wages / convert to hourly rates**

In [99]:
# Check the stats for the annual wages
annual_wages_df = wages_df[(wages_df['annual_flag'] == 1)]
annual_wages_df.shape

(172, 10)

In [100]:
# The number of occupations with an annual wage rate per year
print("Records with annual wage rate per year:")
print(annual_wages_df.groupby('year').size())

Records with annual wage rate per year:
year
2012     8
2013     9
2014    12
2015    13
2016    13
2017    13
2018    13
2019    13
2020    14
2021    14
2022    14
2023    18
2024    18
dtype: int64

In [101]:
# Check unique wage comments for the occupations with annual wage rate
print(annual_wages_df[(annual_wages_df['low_wage'].notna())]['wage_comment'].unique())

['In this occupation, a large number of people are self-employed. For this reason, wages for this occupation are presented at an annual rate to better represent earnings for this occupation.'
 nan
 'In this occupation, a large number of people are self-employed. For this reason, wages for this occupation are presented at an annual rate to better repre'
 'In this occupation, a large number of people are self-employed. For this reason, wages for this occupation are presented at an annual rate to better represent earnings for this occupation. \n'
 'Wages for this occupation are presented at an annual rate to better represent earnings for this occupation.']

Only **8 to 18 occupations per year** (**±3.6% of the total data**) are reported with an annual wage rate. Based on the wage comments, this rate is primarily applied to occupations characterized by high self-employment, where employees typically work irregular hours and an annual figure is used to best represent total earnings.

Given that over 96% of the data is already reported as an hourly wage rate, we decided to standardize the remaining small fraction of annual rates by converting them to hourly units using a standard assumption of **2,000 working hours (40 hours/week×50 weeks/year)**.

- Converting the few annual rates to hourly units is necessary to prevent the exclusion of these occupations and enable direct comparison with the majority of hourly-reported wages.

- For the ≈8 to 18 occupations reported annually due to high self-employment, the resulting hourly wage is an **imputed** (approximate/substitute) value. Although this value relies on the 2,000-hour assumption and may not perfectly reflect the actual irregular working hours, it represents the most practical method for maintaining a consistent hourly metric.

In [102]:
# Standardize all wages to be hourly. Annual wages are divided by 2000 (40h/wk * 50wk/yr).
wage_cols = ['low_wage', 'median_wage', 'high_wage']
for col in wage_cols:
    wages_df[col] = np.where(wages_df['annual_flag'] == 1, wages_df[col] / 2000, wages_df[col])

#### **Check how the NOC codes are represented**

In [103]:
# Convert to string to ensure consistent handling of NOC codes
wages_df['noc_code'] = wages_df['noc_code'].astype(str)

noc_codes = wages_df['noc_code'].unique()

print(f"Total Unique NOC Codes Found: {len(noc_codes)}")
print("-" * 30)

# Print all unique NOC codes
with np.printoptions(threshold=np.inf):
    print(noc_codes)

Total Unique NOC Codes Found: 1709
------------------------------
['11' '12' '13' '14' '15' '16' '111' '112' '113' '114' '121' '122' '123'
 '131' '132' '211' '212' '213' '311' '312' '313' '314' '411' '412' '413'
 '414' '511' '512' '513' '611' '621' '631' '632' '641' '642' '643' '651'
 '711' '712' '713' '721' '811' '911' '912' '1111' '1112' '1113' '1114'
 '1121' '1122' '1211' '1212' '1213' '1214' '1215' '1221' '1222' '1223'
 '1224' '1225' '1226' '1227' '1228' '1231' '1232' '1233' '1234' '1235'
 '1236' '1241' '1242' '1243' '1244' '1411' '1413' '1414' '1422' '1423'
 '1424' '1431' '1432' '1433' '1434' '1435' '1441' '1442' '1443' '1451'
 '1452' '1453' '1454' '1461' '1462' '1463' '1471' '1472' '1473' '1474'
 '1475' '1476' '2111' '2112' '2113' '2114' '2115' '2121' '2122' '2123'
 '2131' '2132' '2133' '2134' '2141' '2142' '2143' '2144' '2145' '2146'
 '2147' '2148' '2151' '2152' '2153' '2154' '2161' '2171' '2172' '2173'
 '2174' '2175' '2211' '2212' '2213' '2221' '2222' '2223' '2224' '2225'
 '2231' '2232' '2233' '2234' '2241' '2242' '2243' '2244' '2251' '2252'
 '2253' '2254' '2255' '2261' '2262' '2263' '2264' '2271' '2272' '2273'
 '2274' '2275' '2281' '2282' '2283' '3111' '3112' '3113' '3114' '3121'
 '3122' '3123' '3131' '3132' '3141' '3142' '3143' '3144' '3151' '3152'
 '3211' '3212' '3213' '3214' '3215' '3216' '3217' '3218' '3219' '3221'
 '3222' '3223' '3231' '3232' '3233' '3234' '3235' '3411' '3413' '3414'
 '4111' '4112' '4121' '4122' '4131' '4141' '4142' '4143' '4151' '4152'
 '4153' '4154' '4155' '4161' '4162' '4163' '4164' '4165' '4166' '4167'
 '4168' '4169' '4211' '4212' '4213' '4214' '4215' '4216' '4217' '5111'
 '5112' '5113' '5121' '5122' '5123' '5124' '5125' '5131' '5132' '5133'
 '5134' '5135' '5136' '5211' '5212' '5221' '5222' '5223' '5224' '5225'
 '5226' '5227' '5231' '5232' '5241' '5242' '5243' '5244' '5245' '5251'
 '5252' '5253' '5254' '6211' '6212' '6213' '6214' '6215' '6216' '6221'
 '6231' '6232' '6233' '6234' '6241' '6242' '6251' '6252' '6261' '6262'
 '6271' '6272' '6411' '6421' '6431' '6432' '6433' '6434' '6435' '6441'
 '6442' '6443' '6451' '6452' '6453' '6461' '6462' '6463' '6464' '6465'
 '6471' '6472' '6474' '6481' '6482' '6483' '6484' '6611' '6621' '6622'
 '6623' '6641' '6651' '6661' '6662' '6663' '6671' '6672' '6681' '6682'
 '6683' '7211' '7212' '7213' '7214' '7215' '7216' '7217' '7218' '7219'
 '7221' '7222' '7231' '7232' '7241' '7242' '7243' '7244' '7245' '7246'
 '7247' '7251' '7252' '7253' '7261' '7262' '7263' '7264' '7265' '7266'
 '7271' '7272' '7281' '7282' '7283' '7284' '7291' '7292' '7293' '7294'
 '7295' '7311' '7312' '7313' '7314' '7315' '7316' '7317' '7318' '7321'
 '7322' '7331' '7332' '7333' '7334' '7335' '7341' '7342' '7343' '7344'
 '7351' '7352' '7361' '7362' '7371' '7372' '7373' '7381' '7382' '7383'
 '7411' '7412' '7413' '7414' '7421' '7422' '7431' '7432' '7433' '7434'
 '7435' '7436' '7437' '7441' '7442' '7443' '7444' '7445' '7451' '7452'
 '7611' '7612' '7621' '7622' '8211' '8221' '8222' '8231' '8232' '8241'
 '8251' '8252' '8253' '8254' '8255' '8256' '8257' '8261' '8262' '8411'
 '8412' '8421' '8422' '8431' '8432' '8441' '8442' '8611' '8612' '8613'
 '8614' '8615' '8616' '9211' '9212' '9213' '9214' '9215' '9216' '9221'
 '9222' '9223' '9224' '9225' '9226' '9227' '9231' '9232' '9233' '9234'
 '9411' '9412' '9413' '9414' '9415' '9421' '9422' '9423' '9424' '9431'
 '9432' '9433' '9434' '9435' '9436' '9441' '9442' '9443' '9444' '9451'
 '9452' '9453' '9454' '9461' '9462' '9463' '9464' '9465' '9471' '9472'
 '9473' '9474' '9481' '9482' '9483' '9484' '9485' '9486' '9487' '9491'
 '9492' '9493' '9494' '9495' '9496' '9497' '9498' '9511' '9512' '9513'
 '9514' '9516' '9517' '9611' '9612' '9613' '9614' '9615' '9616' '9617'
 '9618' '9619' 'NOC_0011' 'NOC_0012' 'NOC_0013' 'NOC_0014' 'NOC_0015'
 'NOC_0016' 'NOC_0111' 'NOC_0112' 'NOC_0113' 'NOC_0114' 'NOC_0121'
 'NOC_0122' 'NOC_0123' 'NOC_0131' 'NOC_0132' 'NOC_0211' 'NOC_0212'
 'NOC_0213' 'NOC_0311' 'NOC_0312' 'NOC_0313' 'NOC_0314' 'NOC_0411'
 'NOC_0412' 'NOC_0413' 'NOC_0414' 'NOC_0511' 'NOC_0512' 'NOC_0513'
 'NOC_0611' 'NOC_0621' 'NOC_0631' 'NOC_0632' 'NOC_0641' 'NOC_0642'
 'NOC_0643' 'NOC_0651' 'NOC_0711' 'NOC_0712' 'NOC_0713' 'NOC_0721'
 'NOC_0811' 'NOC_0911' 'NOC_0912' 'NOC_1111' 'NOC_1112' 'NOC_1113'
 'NOC_1114' 'NOC_1121' 'NOC_1122' 'NOC_1211' 'NOC_1212' 'NOC_1213'
 'NOC_1214' 'NOC_1215' 'NOC_1221' 'NOC_1222' 'NOC_1223' 'NOC_1224'
 'NOC_1225' 'NOC_1226' 'NOC_1227' 'NOC_1228' 'NOC_1231' 'NOC_1232'
 'NOC_1233' 'NOC_1234' 'NOC_1235' 'NOC_1236' 'NOC_1241' 'NOC_1242'
 'NOC_1243' 'NOC_1244' 'NOC_1411' 'NOC_1413' 'NOC_1414' 'NOC_1422'
 'NOC_1423' 'NOC_1424' 'NOC_1431' 'NOC_1432' 'NOC_1433' 'NOC_1434'
 'NOC_1435' 'NOC_1441' 'NOC_1442' 'NOC_1443' 'NOC_1451' 'NOC_1452'
 'NOC_1453' 'NOC_1454' 'NOC_1461' 'NOC_1462' 'NOC_1463' 'NOC_1471'
 'NOC_1472' 'NOC_1473' 'NOC_1474' 'NOC_1475' 'NOC_1476' 'NOC_2111'
 'NOC_2112' 'NOC_2113' 'NOC_2114' 'NOC_2115' 'NOC_2121' 'NOC_2122'
 'NOC_2123' 'NOC_2131' 'NOC_2132' 'NOC_2133' 'NOC_2134' 'NOC_2141'
 'NOC_2142' 'NOC_2143' 'NOC_2144' 'NOC_2145' 'NOC_2146' 'NOC_2147'
 'NOC_2148' 'NOC_2151' 'NOC_2152' 'NOC_2153' 'NOC_2154' 'NOC_2161'
 'NOC_2171' 'NOC_2172' 'NOC_2173' 'NOC_2174' 'NOC_2175' 'NOC_2211'
 'NOC_2212' 'NOC_2213' 'NOC_2221' 'NOC_2222' 'NOC_2223' 'NOC_2224'
 'NOC_2225' 'NOC_2231' 'NOC_2232' 'NOC_2233' 'NOC_2234' 'NOC_2241'
 'NOC_2242' 'NOC_2243' 'NOC_2244' 'NOC_2251' 'NOC_2252' 'NOC_2253'
 'NOC_2254' 'NOC_2255' 'NOC_2261' 'NOC_2262' 'NOC_2263' 'NOC_2264'
 'NOC_2271' 'NOC_2272' 'NOC_2273' 'NOC_2274' 'NOC_2275' 'NOC_2281'
 'NOC_2282' 'NOC_2283' 'NOC_3111' 'NOC_3112' 'NOC_3113' 'NOC_3114'
 'NOC_3121' 'NOC_3122' 'NOC_3123' 'NOC_3131' 'NOC_3132' 'NOC_3141'
 'NOC_3142' 'NOC_3143' 'NOC_3144' 'NOC_3151' 'NOC_3152' 'NOC_3211'
 'NOC_3212' 'NOC_3213' 'NOC_3214' 'NOC_3215' 'NOC_3216' 'NOC_3217'
 'NOC_3218' 'NOC_3219' 'NOC_3221' 'NOC_3222' 'NOC_3223' 'NOC_3231'
 'NOC_3232' 'NOC_3233' 'NOC_3234' 'NOC_3235' 'NOC_3411' 'NOC_3413'
 'NOC_3414' 'NOC_4111' 'NOC_4112' 'NOC_4121' 'NOC_4122' 'NOC_4131'
 'NOC_4141' 'NOC_4142' 'NOC_4143' 'NOC_4151' 'NOC_4152' 'NOC_4153'
 'NOC_4154' 'NOC_4155' 'NOC_4161' 'NOC_4162' 'NOC_4163' 'NOC_4164'
 'NOC_4165' 'NOC_4166' 'NOC_4167' 'NOC_4168' 'NOC_4169' 'NOC_4211'
 'NOC_4212' 'NOC_4213' 'NOC_4214' 'NOC_4215' 'NOC_4216' 'NOC_4217'
 'NOC_5111' 'NOC_5112' 'NOC_5113' 'NOC_5121' 'NOC_5122' 'NOC_5123'
 'NOC_5124' 'NOC_5125' 'NOC_5131' 'NOC_5132' 'NOC_5133' 'NOC_5134'
 'NOC_5135' 'NOC_5136' 'NOC_5211' 'NOC_5212' 'NOC_5221' 'NOC_5222'
 'NOC_5223' 'NOC_5224' 'NOC_5225' 'NOC_5226' 'NOC_5227' 'NOC_5231'
 'NOC_5232' 'NOC_5241' 'NOC_5242' 'NOC_5243' 'NOC_5244' 'NOC_5245'
 'NOC_5251' 'NOC_5252' 'NOC_5253' 'NOC_5254' 'NOC_6211' 'NOC_6212'
 'NOC_6213' 'NOC_6214' 'NOC_6215' 'NOC_6216' 'NOC_6221' 'NOC_6231'
 'NOC_6232' 'NOC_6233' 'NOC_6234' 'NOC_6241' 'NOC_6242' 'NOC_6251'
 'NOC_6252' 'NOC_6261' 'NOC_6262' 'NOC_6271' 'NOC_6272' 'NOC_6411'
 'NOC_6421' 'NOC_6431' 'NOC_6432' 'NOC_6433' 'NOC_6434' 'NOC_6435'
 'NOC_6441' 'NOC_6442' 'NOC_6443' 'NOC_6451' 'NOC_6452' 'NOC_6453'
 'NOC_6461' 'NOC_6462' 'NOC_6463' 'NOC_6464' 'NOC_6465' 'NOC_6471'
 'NOC_6472' 'NOC_6474' 'NOC_6481' 'NOC_6482' 'NOC_6483' 'NOC_6484'
 'NOC_6611' 'NOC_6621' 'NOC_6622' 'NOC_6623' 'NOC_6641' 'NOC_6651'
 'NOC_6661' 'NOC_6662' 'NOC_6663' 'NOC_6671' 'NOC_6672' 'NOC_6681'
 'NOC_6682' 'NOC_6683' 'NOC_7211' 'NOC_7212' 'NOC_7213' 'NOC_7214'
 'NOC_7215' 'NOC_7216' 'NOC_7217' 'NOC_7218' 'NOC_7219' 'NOC_7221'
 'NOC_7222' 'NOC_7231' 'NOC_7232' 'NOC_7241' 'NOC_7242' 'NOC_7243'
 'NOC_7244' 'NOC_7245' 'NOC_7246' 'NOC_7247' 'NOC_7251' 'NOC_7252'
 'NOC_7253' 'NOC_7261' 'NOC_7262' 'NOC_7263' 'NOC_7264' 'NOC_7265'
 'NOC_7266' 'NOC_7271' 'NOC_7272' 'NOC_7281' 'NOC_7282' 'NOC_7283'
 'NOC_7284' 'NOC_7291' 'NOC_7292' 'NOC_7293' 'NOC_7294' 'NOC_7295'
 'NOC_7311' 'NOC_7312' 'NOC_7313' 'NOC_7314' 'NOC_7315' 'NOC_7316'
 'NOC_7317' 'NOC_7318' 'NOC_7321' 'NOC_7322' 'NOC_7331' 'NOC_7332'
 'NOC_7333' 'NOC_7334' 'NOC_7335' 'NOC_7341' 'NOC_7342' 'NOC_7343'
 'NOC_7344' 'NOC_7351' 'NOC_7352' 'NOC_7361' 'NOC_7362' 'NOC_7371'
 'NOC_7372' 'NOC_7373' 'NOC_7381' 'NOC_7382' 'NOC_7383' 'NOC_7411'
 'NOC_7412' 'NOC_7413' 'NOC_7414' 'NOC_7421' 'NOC_7422' 'NOC_7431'
 'NOC_7432' 'NOC_7433' 'NOC_7434' 'NOC_7435' 'NOC_7436' 'NOC_7437'
 'NOC_7441' 'NOC_7442' 'NOC_7443' 'NOC_7444' 'NOC_7445' 'NOC_7451'
 'NOC_7452' 'NOC_7611' 'NOC_7612' 'NOC_7621' 'NOC_7622' 'NOC_8211'
 'NOC_8221' 'NOC_8222' 'NOC_8231' 'NOC_8232' 'NOC_8241' 'NOC_8251'
 'NOC_8252' 'NOC_8253' 'NOC_8254' 'NOC_8255' 'NOC_8256' 'NOC_8257'
 'NOC_8261' 'NOC_8262' 'NOC_8411' 'NOC_8412' 'NOC_8421' 'NOC_8422'
 'NOC_8431' 'NOC_8432' 'NOC_8441' 'NOC_8442' 'NOC_8611' 'NOC_8612'
 'NOC_8613' 'NOC_8614' 'NOC_8615' 'NOC_8616' 'NOC_9211' 'NOC_9212'
 'NOC_9213' 'NOC_9214' 'NOC_9215' 'NOC_9216' 'NOC_9221' 'NOC_9222'
 'NOC_9223' 'NOC_9224' 'NOC_9225' 'NOC_9226' 'NOC_9227' 'NOC_9231'
 'NOC_9232' 'NOC_9233' 'NOC_9234' 'NOC_9411' 'NOC_9412' 'NOC_9413'
 'NOC_9414' 'NOC_9415' 'NOC_9421' 'NOC_9422' 'NOC_9423' 'NOC_9424'
 'NOC_9431' 'NOC_9432' 'NOC_9433' 'NOC_9434' 'NOC_9435' 'NOC_9436'
 'NOC_9441' 'NOC_9442' 'NOC_9443' 'NOC_9444' 'NOC_9451' 'NOC_9452'
 'NOC_9453' 'NOC_9454' 'NOC_9461' 'NOC_9462' 'NOC_9463' 'NOC_9464'
 'NOC_9465' 'NOC_9471' 'NOC_9472' 'NOC_9473' 'NOC_9474' 'NOC_9481'
 'NOC_9482' 'NOC_9483' 'NOC_9484' 'NOC_9485' 'NOC_9486' 'NOC_9487'
 'NOC_9491' 'NOC_9492' 'NOC_9493' 'NOC_9494' 'NOC_9495' 'NOC_9496'
 'NOC_9497' 'NOC_9498' 'NOC_9511' 'NOC_9512' 'NOC_9513' 'NOC_9514'
 'NOC_9516' 'NOC_9517' 'NOC_9611' 'NOC_9612' 'NOC_9613' 'NOC_9614'
 'NOC_9615' 'NOC_9616' 'NOC_9617' 'NOC_9618' 'NOC_9619' 'NOC_0124'
 'NOC_0125' 'NOC_0421' 'NOC_0422' 'NOC_0423' 'NOC_0431' 'NOC_0432'
 'NOC_0433' 'NOC_0601' 'NOC_0714' 'NOC_0731' 'NOC_0821' 'NOC_0822'
 'NOC_0823' 'NOC_1123' 'NOC_1251' 'NOC_1252' 'NOC_1253' 'NOC_1254'
 'NOC_1311' 'NOC_1312' 'NOC_1313' 'NOC_1314' 'NOC_1315' 'NOC_1415'
 'NOC_1416' 'NOC_1511' 'NOC_1512' 'NOC_1513' 'NOC_1521' 'NOC_1522'
 'NOC_1523' 'NOC_1524' 'NOC_1525' 'NOC_1526' 'NOC_3011' 'NOC_3012'
 'NOC_3124' 'NOC_3125' 'NOC_3236' 'NOC_3237' 'NOC_4011' 'NOC_4012'
 'NOC_4021' 'NOC_4031' 'NOC_4032' 'NOC_4033' 'NOC_4156' 'NOC_4311'
 'NOC_4312' 'NOC_4313' 'NOC_4411' 'NOC_4412' 'NOC_4413' 'NOC_4421'
 'NOC_4422' 'NOC_4423' 'NOC_6222' 'NOC_6235' 'NOC_6311' 'NOC_6312'
 'NOC_6313' 'NOC_6314' 'NOC_6315' 'NOC_6316' 'NOC_6321' 'NOC_6322'
 'NOC_6331' 'NOC_6332' 'NOC_6341' 'NOC_6342' 'NOC_6343' 'NOC_6344'
 'NOC_6345' 'NOC_6346' 'NOC_6511' 'NOC_6512' 'NOC_6513' 'NOC_6521'
 'NOC_6522' 'NOC_6523' 'NOC_6524' 'NOC_6525' 'NOC_6531' 'NOC_6532'
 'NOC_6533' 'NOC_6541' 'NOC_6551' 'NOC_6552' 'NOC_6561' 'NOC_6562'
 'NOC_6563' 'NOC_6564' 'NOC_6711' 'NOC_6721' 'NOC_6722' 'NOC_6731'
 'NOC_6732' 'NOC_6733' 'NOC_6741' 'NOC_6742' 'NOC_7201' 'NOC_7202'
 'NOC_7203' 'NOC_7204' 'NOC_7205' 'NOC_7233' 'NOC_7234' 'NOC_7235'
 'NOC_7236' 'NOC_7237' 'NOC_7301' 'NOC_7302' 'NOC_7303' 'NOC_7304'
 'NOC_7305' 'NOC_7384' 'NOC_7511' 'NOC_7512' 'NOC_7513' 'NOC_7514'
 'NOC_7521' 'NOC_7522' 'NOC_7531' 'NOC_7532' 'NOC_7533' 'NOC_7534'
 'NOC_7535' 'NOC_9217' 'NOC_9235' 'NOC_9241' 'NOC_9243' 'NOC_9416'
 'NOC_9417' 'NOC_9418' 'NOC_9437' 'NOC_9445' 'NOC_9446' 'NOC_9447'
 'NOC_9521' 'NOC_9522' 'NOC_9523' 'NOC_9524' 'NOC_9525' 'NOC_9526'
 'NOC_9527' 'NOC_9531' 'NOC_9532' 'NOC_9533' 'NOC_9534' 'NOC_9535'
 'NOC_9536' 'NOC_9537' 'NOC_00010' 'NOC_00011' 'NOC_00012' 'NOC_00013'
 'NOC_00014' 'NOC_00015' 'NOC_10010' 'NOC_10011' 'NOC_10012' 'NOC_10019'
 'NOC_10020' 'NOC_10021' 'NOC_10022' 'NOC_10029' 'NOC_10030' 'NOC_11100'
 'NOC_11101' 'NOC_11102' 'NOC_11103' 'NOC_11109' 'NOC_11200' 'NOC_11201'
 'NOC_11202' 'NOC_12010' 'NOC_12011' 'NOC_12012' 'NOC_12013' 'NOC_12100'
 'NOC_12101' 'NOC_12102' 'NOC_12103' 'NOC_12104' 'NOC_12110' 'NOC_12111'
 'NOC_12112' 'NOC_12113' 'NOC_12200' 'NOC_12201' 'NOC_12202' 'NOC_12203'
 'NOC_13100' 'NOC_13101' 'NOC_13102' 'NOC_13110' 'NOC_13111' 'NOC_13112'
 'NOC_13200' 'NOC_13201' 'NOC_14100' 'NOC_14101' 'NOC_14102' 'NOC_14103'
 'NOC_14110' 'NOC_14111' 'NOC_14112' 'NOC_14200' 'NOC_14201' 'NOC_14202'
 'NOC_14300' 'NOC_14301' 'NOC_14400' 'NOC_14401' 'NOC_14402' 'NOC_14403'
 'NOC_14404' 'NOC_14405' 'NOC_20010' 'NOC_20011' 'NOC_20012' 'NOC_21100'
 'NOC_21101' 'NOC_21102' 'NOC_21103' 'NOC_21109' 'NOC_21110' 'NOC_21111'
 'NOC_21112' 'NOC_21120' 'NOC_21200' 'NOC_21201' 'NOC_21202' 'NOC_21203'
 'NOC_21210' 'NOC_21211' 'NOC_21220' 'NOC_21221' 'NOC_21222' 'NOC_21223'
 'NOC_21230' 'NOC_21231' 'NOC_21232' 'NOC_21233' 'NOC_21234' 'NOC_21300'
 'NOC_21301' 'NOC_21310' 'NOC_21311' 'NOC_21320' 'NOC_21321' 'NOC_21322'
 'NOC_21330' 'NOC_21331' 'NOC_21332' 'NOC_21390' 'NOC_21399' 'NOC_22100'
 'NOC_22101' 'NOC_22110' 'NOC_22111' 'NOC_22112' 'NOC_22113' 'NOC_22114'
 'NOC_22210' 'NOC_22211' 'NOC_22212' 'NOC_22213' 'NOC_22214' 'NOC_22220'
 'NOC_22221' 'NOC_22222' 'NOC_22230' 'NOC_22231' 'NOC_22232' 'NOC_22233'
 'NOC_22300' 'NOC_22301' 'NOC_22302' 'NOC_22303' 'NOC_22310' 'NOC_22311'
 'NOC_22312' 'NOC_22313' 'NOC_30010' 'NOC_31100' 'NOC_31101' 'NOC_31102'
 'NOC_31103' 'NOC_31110' 'NOC_31111' 'NOC_31112' 'NOC_31120' 'NOC_31121'
 'NOC_31200' 'NOC_31201' 'NOC_31202' 'NOC_31203' 'NOC_31204' 'NOC_31209'
 'NOC_31300' 'NOC_31301' 'NOC_31302' 'NOC_31303' 'NOC_32100' 'NOC_32101'
 'NOC_32102' 'NOC_32103' 'NOC_32104' 'NOC_32109' 'NOC_32110' 'NOC_32111'
 'NOC_32112' 'NOC_32120' 'NOC_32121' 'NOC_32122' 'NOC_32123' 'NOC_32124'
 'NOC_32129' 'NOC_32200' 'NOC_32201' 'NOC_32209' 'NOC_33100' 'NOC_33101'
 'NOC_33102' 'NOC_33103' 'NOC_33109' 'NOC_40010' 'NOC_40011' 'NOC_40012'
 'NOC_40019' 'NOC_40020' 'NOC_40021' 'NOC_40030' 'NOC_40040' 'NOC_40041'
 'NOC_40042' 'NOC_41100' 'NOC_41101' 'NOC_41200' 'NOC_41201' 'NOC_41210'
 'NOC_41220' 'NOC_41221' 'NOC_41300' 'NOC_41301' 'NOC_41302' 'NOC_41310'
 'NOC_41311' 'NOC_41320' 'NOC_41321' 'NOC_41400' 'NOC_41401' 'NOC_41402'
 'NOC_41403' 'NOC_41404' 'NOC_41405' 'NOC_41406' 'NOC_41407' 'NOC_41409'
 'NOC_42100' 'NOC_42101' 'NOC_42102' 'NOC_42200' 'NOC_42201' 'NOC_42202'
 'NOC_42203' 'NOC_42204' 'NOC_43100' 'NOC_43109' 'NOC_43200' 'NOC_43201'
 'NOC_43202' 'NOC_43203' 'NOC_43204' 'NOC_44100' 'NOC_44101' 'NOC_44200'
 'NOC_45100' 'NOC_50010' 'NOC_50011' 'NOC_50012' 'NOC_51100' 'NOC_51101'
 'NOC_51102' 'NOC_51110' 'NOC_51111' 'NOC_51112' 'NOC_51113' 'NOC_51114'
 'NOC_51120' 'NOC_51121' 'NOC_51122' 'NOC_52100' 'NOC_52110' 'NOC_52111'
 'NOC_52112' 'NOC_52113' 'NOC_52114' 'NOC_52119' 'NOC_52120' 'NOC_52121'
 'NOC_53100' 'NOC_53110' 'NOC_53111' 'NOC_53120' 'NOC_53121' 'NOC_53122'
 'NOC_53123' 'NOC_53124' 'NOC_53125' 'NOC_53200' 'NOC_53201' 'NOC_53202'
 'NOC_54100' 'NOC_55109' 'NOC_60010' 'NOC_60020' 'NOC_60030' 'NOC_60031'
 'NOC_60040' 'NOC_62010' 'NOC_62020' 'NOC_62021' 'NOC_62022' 'NOC_62023'
 'NOC_62024' 'NOC_62029' 'NOC_62100' 'NOC_62101' 'NOC_62200' 'NOC_62201'
 'NOC_62202' 'NOC_63100' 'NOC_63101' 'NOC_63102' 'NOC_63200' 'NOC_63201'
 'NOC_63202' 'NOC_63210' 'NOC_63211' 'NOC_63220' 'NOC_63221' 'NOC_64100'
 'NOC_64101' 'NOC_64200' 'NOC_64201' 'NOC_64300' 'NOC_64301' 'NOC_64310'
 'NOC_64311' 'NOC_64312' 'NOC_64313' 'NOC_64314' 'NOC_64320' 'NOC_64321'
 'NOC_64322' 'NOC_64400' 'NOC_64401' 'NOC_64409' 'NOC_64410' 'NOC_65100'
 'NOC_65101' 'NOC_65102' 'NOC_65109' 'NOC_65200' 'NOC_65201' 'NOC_65202'
 'NOC_65210' 'NOC_65211' 'NOC_65220' 'NOC_65229' 'NOC_65310' 'NOC_65311'
 'NOC_65312' 'NOC_65320' 'NOC_65329' 'NOC_70010' 'NOC_70011' 'NOC_70012'
 'NOC_70020' 'NOC_70021' 'NOC_72010' 'NOC_72011' 'NOC_72012' 'NOC_72013'
 'NOC_72014' 'NOC_72020' 'NOC_72021' 'NOC_72022' 'NOC_72023' 'NOC_72024'
 'NOC_72025' 'NOC_72100' 'NOC_72101' 'NOC_72102' 'NOC_72103' 'NOC_72104'
 'NOC_72105' 'NOC_72106' 'NOC_72200' 'NOC_72201' 'NOC_72202' 'NOC_72203'
 'NOC_72204' 'NOC_72205' 'NOC_72300' 'NOC_72301' 'NOC_72302' 'NOC_72310'
 'NOC_72311' 'NOC_72320' 'NOC_72321' 'NOC_72400' 'NOC_72401' 'NOC_72402'
 'NOC_72403' 'NOC_72404' 'NOC_72405' 'NOC_72406' 'NOC_72410' 'NOC_72411'
 'NOC_72420' 'NOC_72421' 'NOC_72422' 'NOC_72423' 'NOC_72429' 'NOC_72500'
 'NOC_72501' 'NOC_72600' 'NOC_72601' 'NOC_72602' 'NOC_72603' 'NOC_72604'
 'NOC_72999' 'NOC_73100' 'NOC_73101' 'NOC_73102' 'NOC_73110' 'NOC_73111'
 'NOC_73112' 'NOC_73113' 'NOC_73200' 'NOC_73201' 'NOC_73202' 'NOC_73209'
 'NOC_73300' 'NOC_73301' 'NOC_73310' 'NOC_73311' 'NOC_73400' 'NOC_73401'
 'NOC_73402' 'NOC_74100' 'NOC_74101' 'NOC_74102' 'NOC_74200' 'NOC_74201'
 'NOC_74202' 'NOC_74203' 'NOC_74204' 'NOC_74205' 'NOC_75100' 'NOC_75101'
 'NOC_75110' 'NOC_75119' 'NOC_75200' 'NOC_75201' 'NOC_75210' 'NOC_75211'
 'NOC_75212' 'NOC_80010' 'NOC_80020' 'NOC_80021' 'NOC_80022' 'NOC_82010'
 'NOC_82020' 'NOC_82021' 'NOC_82030' 'NOC_82031' 'NOC_83100' 'NOC_83101'
 'NOC_83110' 'NOC_83120' 'NOC_83121' 'NOC_84100' 'NOC_84101' 'NOC_84110'
 'NOC_84111' 'NOC_84120' 'NOC_84121' 'NOC_85100' 'NOC_85101' 'NOC_85102'
 'NOC_85103' 'NOC_85104' 'NOC_85110' 'NOC_85111' 'NOC_85120' 'NOC_85121'
 'NOC_90010' 'NOC_90011' 'NOC_92010' 'NOC_92011' 'NOC_92012' 'NOC_92013'
 'NOC_92014' 'NOC_92015' 'NOC_92020' 'NOC_92021' 'NOC_92022' 'NOC_92023'
 'NOC_92024' 'NOC_92100' 'NOC_92101' 'NOC_93100' 'NOC_93101' 'NOC_93102'
 'NOC_93200' 'NOC_94100' 'NOC_94101' 'NOC_94102' 'NOC_94103' 'NOC_94104'
 'NOC_94105' 'NOC_94106' 'NOC_94107' 'NOC_94110' 'NOC_94111' 'NOC_94112'
 'NOC_94120' 'NOC_94121' 'NOC_94122' 'NOC_94123' 'NOC_94124' 'NOC_94129'
 'NOC_94130' 'NOC_94131' 'NOC_94132' 'NOC_94133' 'NOC_94140' 'NOC_94141'
 'NOC_94142' 'NOC_94143' 'NOC_94150' 'NOC_94151' 'NOC_94152' 'NOC_94153'
 'NOC_94200' 'NOC_94201' 'NOC_94202' 'NOC_94203' 'NOC_94204' 'NOC_94205'
 'NOC_94210' 'NOC_94211' 'NOC_94212' 'NOC_94213' 'NOC_94219' 'NOC_95100'
 'NOC_95101' 'NOC_95102' 'NOC_95103' 'NOC_95104' 'NOC_95105' 'NOC_95106'
 'NOC_95107' 'NOC_95109']

For consistency and ease of later analysis, we will ensure the NOC codes contain only the numeric values (by stripping any textual prefixes).   
We can also see that some NOC codes are shorter than expected (< 4 digits), indicating that leading zeros were dropped.These zeros are essential for identifying the major occupational group (the first digit).

In [104]:
# Clean the NOC codes
wages_df['noc_code'] = wages_df['noc_code'].str.replace('NOC_', '', case=False, regex=False)

# If code length is 2 or 3 -> pad to 4 digits (e.g., "11" -> "0011") 
wages_df['noc_code'] = wages_df['noc_code'].apply(lambda x: x.zfill(4) if len(x) <= 3 else x)

# Check the NOC codes
noc_codes = wages_df['noc_code'].unique()
# Print all unique NOC codes
with np.printoptions(threshold=np.inf):
    print(noc_codes)

['0011' '0012' '0013' '0014' '0015' '0016' '0111' '0112' '0113' '0114'
 '0121' '0122' '0123' '0131' '0132' '0211' '0212' '0213' '0311' '0312'
 '0313' '0314' '0411' '0412' '0413' '0414' '0511' '0512' '0513' '0611'
 '0621' '0631' '0632' '0641' '0642' '0643' '0651' '0711' '0712' '0713'
 '0721' '0811' '0911' '0912' '1111' '1112' '1113' '1114' '1121' '1122'
 '1211' '1212' '1213' '1214' '1215' '1221' '1222' '1223' '1224' '1225'
 '1226' '1227' '1228' '1231' '1232' '1233' '1234' '1235' '1236' '1241'
 '1242' '1243' '1244' '1411' '1413' '1414' '1422' '1423' '1424' '1431'
 '1432' '1433' '1434' '1435' '1441' '1442' '1443' '1451' '1452' '1453'
 '1454' '1461' '1462' '1463' '1471' '1472' '1473' '1474' '1475' '1476'
 '2111' '2112' '2113' '2114' '2115' '2121' '2122' '2123' '2131' '2132'
 '2133' '2134' '2141' '2142' '2143' '2144' '2145' '2146' '2147' '2148'
 '2151' '2152' '2153' '2154' '2161' '2171' '2172' '2173' '2174' '2175'
 '2211' '2212' '2213' '2221' '2222' '2223' '2224' '2225' '2231' '2232'
 '2233' '2234' '2241' '2242' '2243' '2244' '2251' '2252' '2253' '2254'
 '2255' '2261' '2262' '2263' '2264' '2271' '2272' '2273' '2274' '2275'
 '2281' '2282' '2283' '3111' '3112' '3113' '3114' '3121' '3122' '3123'
 '3131' '3132' '3141' '3142' '3143' '3144' '3151' '3152' '3211' '3212'
 '3213' '3214' '3215' '3216' '3217' '3218' '3219' '3221' '3222' '3223'
 '3231' '3232' '3233' '3234' '3235' '3411' '3413' '3414' '4111' '4112'
 '4121' '4122' '4131' '4141' '4142' '4143' '4151' '4152' '4153' '4154'
 '4155' '4161' '4162' '4163' '4164' '4165' '4166' '4167' '4168' '4169'
 '4211' '4212' '4213' '4214' '4215' '4216' '4217' '5111' '5112' '5113'
 '5121' '5122' '5123' '5124' '5125' '5131' '5132' '5133' '5134' '5135'
 '5136' '5211' '5212' '5221' '5222' '5223' '5224' '5225' '5226' '5227'
 '5231' '5232' '5241' '5242' '5243' '5244' '5245' '5251' '5252' '5253'
 '5254' '6211' '6212' '6213' '6214' '6215' '6216' '6221' '6231' '6232'
 '6233' '6234' '6241' '6242' '6251' '6252' '6261' '6262' '6271' '6272'
 '6411' '6421' '6431' '6432' '6433' '6434' '6435' '6441' '6442' '6443'
 '6451' '6452' '6453' '6461' '6462' '6463' '6464' '6465' '6471' '6472'
 '6474' '6481' '6482' '6483' '6484' '6611' '6621' '6622' '6623' '6641'
 '6651' '6661' '6662' '6663' '6671' '6672' '6681' '6682' '6683' '7211'
 '7212' '7213' '7214' '7215' '7216' '7217' '7218' '7219' '7221' '7222'
 '7231' '7232' '7241' '7242' '7243' '7244' '7245' '7246' '7247' '7251'
 '7252' '7253' '7261' '7262' '7263' '7264' '7265' '7266' '7271' '7272'
 '7281' '7282' '7283' '7284' '7291' '7292' '7293' '7294' '7295' '7311'
 '7312' '7313' '7314' '7315' '7316' '7317' '7318' '7321' '7322' '7331'
 '7332' '7333' '7334' '7335' '7341' '7342' '7343' '7344' '7351' '7352'
 '7361' '7362' '7371' '7372' '7373' '7381' '7382' '7383' '7411' '7412'
 '7413' '7414' '7421' '7422' '7431' '7432' '7433' '7434' '7435' '7436'
 '7437' '7441' '7442' '7443' '7444' '7445' '7451' '7452' '7611' '7612'
 '7621' '7622' '8211' '8221' '8222' '8231' '8232' '8241' '8251' '8252'
 '8253' '8254' '8255' '8256' '8257' '8261' '8262' '8411' '8412' '8421'
 '8422' '8431' '8432' '8441' '8442' '8611' '8612' '8613' '8614' '8615'
 '8616' '9211' '9212' '9213' '9214' '9215' '9216' '9221' '9222' '9223'
 '9224' '9225' '9226' '9227' '9231' '9232' '9233' '9234' '9411' '9412'
 '9413' '9414' '9415' '9421' '9422' '9423' '9424' '9431' '9432' '9433'
 '9434' '9435' '9436' '9441' '9442' '9443' '9444' '9451' '9452' '9453'
 '9454' '9461' '9462' '9463' '9464' '9465' '9471' '9472' '9473' '9474'
 '9481' '9482' '9483' '9484' '9485' '9486' '9487' '9491' '9492' '9493'
 '9494' '9495' '9496' '9497' '9498' '9511' '9512' '9513' '9514' '9516'
 '9517' '9611' '9612' '9613' '9614' '9615' '9616' '9617' '9618' '9619'
 '0124' '0125' '0421' '0422' '0423' '0431' '0432' '0433' '0601' '0714'
 '0731' '0821' '0822' '0823' '1123' '1251' '1252' '1253' '1254' '1311'
 '1312' '1313' '1314' '1315' '1415' '1416' '1511' '1512' '1513' '1521'
 '1522' '1523' '1524' '1525' '1526' '3011' '3012' '3124' '3125' '3236'
 '3237' '4011' '4012' '4021' '4031' '4032' '4033' '4156' '4311' '4312'
 '4313' '4411' '4412' '4413' '4421' '4422' '4423' '6222' '6235' '6311'
 '6312' '6313' '6314' '6315' '6316' '6321' '6322' '6331' '6332' '6341'
 '6342' '6343' '6344' '6345' '6346' '6511' '6512' '6513' '6521' '6522'
 '6523' '6524' '6525' '6531' '6532' '6533' '6541' '6551' '6552' '6561'
 '6562' '6563' '6564' '6711' '6721' '6722' '6731' '6732' '6733' '6741'
 '6742' '7201' '7202' '7203' '7204' '7205' '7233' '7234' '7235' '7236'
 '7237' '7301' '7302' '7303' '7304' '7305' '7384' '7511' '7512' '7513'
 '7514' '7521' '7522' '7531' '7532' '7533' '7534' '7535' '9217' '9235'
 '9241' '9243' '9416' '9417' '9418' '9437' '9445' '9446' '9447' '9521'
 '9522' '9523' '9524' '9525' '9526' '9527' '9531' '9532' '9533' '9534'
 '9535' '9536' '9537' '00010' '00011' '00012' '00013' '00014' '00015'
 '10010' '10011' '10012' '10019' '10020' '10021' '10022' '10029' '10030'
 '11100' '11101' '11102' '11103' '11109' '11200' '11201' '11202' '12010'
 '12011' '12012' '12013' '12100' '12101' '12102' '12103' '12104' '12110'
 '12111' '12112' '12113' '12200' '12201' '12202' '12203' '13100' '13101'
 '13102' '13110' '13111' '13112' '13200' '13201' '14100' '14101' '14102'
 '14103' '14110' '14111' '14112' '14200' '14201' '14202' '14300' '14301'
 '14400' '14401' '14402' '14403' '14404' '14405' '20010' '20011' '20012'
 '21100' '21101' '21102' '21103' '21109' '21110' '21111' '21112' '21120'
 '21200' '21201' '21202' '21203' '21210' '21211' '21220' '21221' '21222'
 '21223' '21230' '21231' '21232' '21233' '21234' '21300' '21301' '21310'
 '21311' '21320' '21321' '21322' '21330' '21331' '21332' '21390' '21399'
 '22100' '22101' '22110' '22111' '22112' '22113' '22114' '22210' '22211'
 '22212' '22213' '22214' '22220' '22221' '22222' '22230' '22231' '22232'
 '22233' '22300' '22301' '22302' '22303' '22310' '22311' '22312' '22313'
 '30010' '31100' '31101' '31102' '31103' '31110' '31111' '31112' '31120'
 '31121' '31200' '31201' '31202' '31203' '31204' '31209' '31300' '31301'
 '31302' '31303' '32100' '32101' '32102' '32103' '32104' '32109' '32110'
 '32111' '32112' '32120' '32121' '32122' '32123' '32124' '32129' '32200'
 '32201' '32209' '33100' '33101' '33102' '33103' '33109' '40010' '40011'
 '40012' '40019' '40020' '40021' '40030' '40040' '40041' '40042' '41100'
 '41101' '41200' '41201' '41210' '41220' '41221' '41300' '41301' '41302'
 '41310' '41311' '41320' '41321' '41400' '41401' '41402' '41403' '41404'
 '41405' '41406' '41407' '41409' '42100' '42101' '42102' '42200' '42201'
 '42202' '42203' '42204' '43100' '43109' '43200' '43201' '43202' '43203'
 '43204' '44100' '44101' '44200' '45100' '50010' '50011' '50012' '51100'
 '51101' '51102' '51110' '51111' '51112' '51113' '51114' '51120' '51121'
 '51122' '52100' '52110' '52111' '52112' '52113' '52114' '52119' '52120'
 '52121' '53100' '53110' '53111' '53120' '53121' '53122' '53123' '53124'
 '53125' '53200' '53201' '53202' '54100' '55109' '60010' '60020' '60030'
 '60031' '60040' '62010' '62020' '62021' '62022' '62023' '62024' '62029'
 '62100' '62101' '62200' '62201' '62202' '63100' '63101' '63102' '63200'
 '63201' '63202' '63210' '63211' '63220' '63221' '64100' '64101' '64200'
 '64201' '64300' '64301' '64310' '64311' '64312' '64313' '64314' '64320'
 '64321' '64322' '64400' '64401' '64409' '64410' '65100' '65101' '65102'
 '65109' '65200' '65201' '65202' '65210' '65211' '65220' '65229' '65310'
 '65311' '65312' '65320' '65329' '70010' '70011' '70012' '70020' '70021'
 '72010' '72011' '72012' '72013' '72014' '72020' '72021' '72022' '72023'
 '72024' '72025' '72100' '72101' '72102' '72103' '72104' '72105' '72106'
 '72200' '72201' '72202' '72203' '72204' '72205' '72300' '72301' '72302'
 '72310' '72311' '72320' '72321' '72400' '72401' '72402' '72403' '72404'
 '72405' '72406' '72410' '72411' '72420' '72421' '72422' '72423' '72429'
 '72500' '72501' '72600' '72601' '72602' '72603' '72604' '72999' '73100'
 '73101' '73102' '73110' '73111' '73112' '73113' '73200' '73201' '73202'
 '73209' '73300' '73301' '73310' '73311' '73400' '73401' '73402' '74100'
 '74101' '74102' '74200' '74201' '74202' '74203' '74204' '74205' '75100'
 '75101' '75110' '75119' '75200' '75201' '75210' '75211' '75212' '80010'
 '80020' '80021' '80022' '82010' '82020' '82021' '82030' '82031' '83100'
 '83101' '83110' '83120' '83121' '84100' '84101' '84110' '84111' '84120'
 '84121' '85100' '85101' '85102' '85103' '85104' '85110' '85111' '85120'
 '85121' '90010' '90011' '92010' '92011' '92012' '92013' '92014' '92015'
 '92020' '92021' '92022' '92023' '92024' '92100' '92101' '93100' '93101'
 '93102' '93200' '94100' '94101' '94102' '94103' '94104' '94105' '94106'
 '94107' '94110' '94111' '94112' '94120' '94121' '94122' '94123' '94124'
 '94129' '94130' '94131' '94132' '94133' '94140' '94141' '94142' '94143'
 '94150' '94151' '94152' '94153' '94200' '94201' '94202' '94203' '94204'
 '94205' '94210' '94211' '94212' '94213' '94219' '95100' '95101' '95102'
 '95103' '95104' '95105' '95106' '95107' '95109']

 The formatting of the NOC codes is now standardized.

#### **Missing values handling**

 Check the number of missing values per column

In [105]:
# Check the number of missing values per column
print(wages_df.isna().sum())

year               0
noc_code           0
noc_title          0
er_code            0
er_name            0
low_wage           5
median_wage        5
high_wage          5
annual_flag        0
wage_comment    6447
dtype: int64

In [106]:
# Define the wage columns to check for missing values
wage_cols = ['low_wage', 'median_wage', 'high_wage']

# Create a boolean mask: True if ANY of the wage columns is null (NaN)
nan_wage_mask = wages_df[wage_cols].isnull().any(axis=1)

# Filter the DataFrame using the mask and display the head of the resulting records
print("Records where at least one wage column is missing (NaN):")
print(wages_df[nan_wage_mask].head(20).to_string())

Records where at least one wage column is missing (NaN):
        year noc_code                                                                                        noc_title er_code er_name  low_wage  median_wage  high_wage  annual_flag                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 wage_comment
279156  2018     3111                                                                            Specialist physicians    ER00  Canada       NaN          NaN        NaN            1  Due to data limitations, wages for this occupation cannot be published. Physicians are part of a group with special characteristics that make it difficult to accurately ascertain their wage information, as they are predominately paid at a rate negotiated between the provinces and their medical associations. In addition, many are self-employed individuals with an incorporated business, which makes it harder to obtain reliable and consistent source of information from either surveys or public administrative data, reflecting wages in the labour market.
279242  2018     3112                                                      General practitioners and family physicians    ER00  Canada       NaN          NaN        NaN            1  Due to data limitations, wages for this occupation cannot be published. Physicians are part of a group with special characteristics that make it difficult to accurately ascertain their wage information, as they are predominately paid at a rate negotiated between the provinces and their medical associations. In addition, many are self-employed individuals with an incorporated business, which makes it harder to obtain reliable and consistent source of information from either surveys or public administrative data, reflecting wages in the labour market.
480138  2023    00013  Senior managers - health, education, social and community services and membership organizations    ER00  Canada       NaN          NaN        NaN            0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          NaN
524514  2024    00013  Senior managers - health, education, social and community services and membership organizations    ER00  Canada       NaN          NaN        NaN            0                                                                                                                                                                                                                                                                  Due to data limitations, the wage for this occupation cannot be published. These occupations are part of a group with a lot of unique characteristics that make it difficult to accurately ascertain their wage information as physicians are predominately paid at a rate negotiated between the provinces
549110  2024    63220                                                                    Shoe repairers and shoemakers    ER00  Canada       NaN          NaN        NaN            0                                                                                                                                                                                                                                                                  Due to data limitations, the wage for this occupation cannot be published. These occupations are part of a group with a lot of unique characteristics that make it difficult to accurately ascertain their wage information as physicians are predominately paid at a rate negotiated between the provinces


The rows with missing wage values are all subject to data suppression by the source. As confirmed by the comments, wages are omitted because these occupations have unique characteristics that make it difficult to accurately ascertain their wage information.

Since the actual wages are unknown and can't be guessed accurately and comprise only a small fraction of all data (only 5 out of over 6,600 records have missing wages), the best choice is to drop these records.

In [107]:
# Drop the records with the missing wage values
wages_df.dropna(subset=wage_cols, how='all', inplace=True)

#### **Sanity check: summary statistics**

In [108]:
# Define the wage columns
wage_cols = ['low_wage', 'median_wage', 'high_wage']

# Group the DataFrame by year and apply the .describe() method to get summary statistics
wage_summary = wages_df.groupby('year')[wage_cols].describe()

print("Summary Statistics by Year for All Wages (Low, Median, and High):")
print(wage_summary.to_string())

Summary Statistics by Year for All Wages (Low, Median, and High):
     low_wage                                                                          median_wage                                                                          high_wage
        count       mean          std       min      25%     50%      75%          max       count        mean          std    min      25%     50%        75%          max     count        mean          std    min      25%     50%      75%            max
year
2012    520.0  14.429802     4.266255   7.50000  11.0000  14.000  17.0000     33.52000       520.0   24.113750     8.940115  10.00  17.5000  22.680  29.075000     82.27550     520.0   37.487837    16.042033  12.00  27.0350  34.985  43.5900     189.847000
2013    520.0  99.453738  1365.336929   9.75000  11.0000  14.000  17.5000  22765.60000       520.0  207.021683  2961.574755  10.25  18.0000  23.000  29.922500  53279.00000     520.0  439.211937  6462.287416  13.00  28.0000  35.000  45.0650  107062.000000
2014    520.0  15.047976     4.585845  10.00000  11.0000  14.000  18.0000     47.82300       520.0   25.206290    10.033384  10.30  18.0000  23.445  30.228750    108.49000     520.0   39.271190    17.318670  14.25  28.8250  36.000  45.6700     188.230500
2015    520.0  15.519690     4.641671  10.28878  11.5300  15.000  18.0000     47.82000       520.0   25.894273    10.131137  10.30  18.7325  24.290  31.384125    108.49000     520.0   40.249622    17.769394  14.50  29.0000  37.020  47.2175     188.230500
2016    500.0  15.850429     4.678832   4.87050  12.0000  15.000  18.5245     47.82283       500.0   26.557439    10.293346  10.50  19.1825  25.000  32.547500    108.49339     500.0   41.586175    18.006857  14.67  30.0000  38.270  49.0100     188.230500
2017    500.0  16.252625     4.860862  10.85000  12.0000  15.000  19.2300     47.82000       500.0   27.042444    10.480206  10.85  19.8700  25.000  33.347500    108.49000     500.0   42.286107    18.572035  15.00  30.0000  38.585  49.5300     188.230500
2018    498.0  16.706082     5.238904  11.00000  12.6775  15.530  20.0000     65.66000       498.0   27.542573    10.879852  11.40  20.0000  25.635  33.885500    135.65000     498.0   42.329348    17.624409  15.00  30.3150  38.955  50.0000     148.850000
2019    500.0  17.351565     5.535131  11.32000  13.5375  16.000  20.0000     65.66000       500.0   28.410953    12.356201  12.00  20.0000  26.000  34.032500    138.61641     500.0   44.029573    22.133207  15.87  30.9775  40.000  51.2800     277.299230
2020    500.0  18.286562     7.193070  11.45000  14.0000  16.830  21.0000    127.25900       500.0   29.242940    12.941033  13.50  21.0000  26.585  35.000000    153.23800     500.0   44.930155    22.470746  16.00  31.4825  40.405  52.0000     280.017750
2021    500.0  19.029456     7.355771  11.75000  14.9975  17.500  22.0000    127.25900       500.0   30.056875    13.677755  14.00  21.1200  27.470  36.000000    175.29316     500.0   45.860224    22.983886  16.50  32.6275  41.700  52.7825     290.173220
2022    500.0  19.859549     7.337889  13.00000  15.0000  18.275  23.0050    127.25900       500.0   30.900923    13.759344  14.00  22.0000  28.315  37.165000    177.76830     500.0   46.886506    23.197751  17.00  33.0000  42.520  54.9625     278.683195
2023    515.0  21.083063     8.704968  14.00000  16.0000  19.230  24.0200    155.00000       515.0   32.335083    15.640541  14.25  22.5300  29.680  38.460000    189.65950     515.0   49.242320    26.982673  18.00  34.0000  45.000  57.6450     369.694000
2024    514.0  22.044163     9.009617  15.00000  16.7475  20.000  25.0000    155.00000       514.0   33.509305    16.482196  15.00  23.5625  30.290  40.000000    211.53750     514.0   50.748395    28.466432  18.50  34.6050  45.585  58.9700     388.262500

The are abnormally high values in the 2013 summary statistics, so we need to locate the outliers responsible for the extreme right skew.

In [109]:
# Filter the DataFrame for the year 2013 AND a high_wage to find the outlier(s)
anomaly_records = wages_df[(wages_df['year'] == 2013) & (wages_df['high_wage'] > 500)] # Use a high threshold to capture the annual salary outliers

print("Record(s) causing the 2013 wage anomaly:")
# Display relevant columns to confirm the error and identify the NOC code
print(anomaly_records[['year', 'noc_code', 'noc_title', 'low_wage', 'median_wage', 'high_wage', 'annual_flag']].to_string())

Record(s) causing the 2013 wage anomaly:
       year noc_code                                                         noc_title  low_wage  median_wage  high_wage  annual_flag
59254  2013     3123  Other Professional Occupations in Health Diagnosing and Treating   21312.9      41658.0   107062.0            0
60802  2013     3221                                                        Denturists   22765.6      53279.0   101544.0            0

A data error in 2013 was caused by two specific records. Since the wage values exceed $20,000 (for the low wage) / $100,000 (for high wage), we believe that they are most likely unconverted annual salaries that were incorrectly marked as hourly in the source file (annual_flag=0). To correct this error, we will manually force the conversion of these two specific records to hourly rates by dividing their values by the 2,000-hour standard.

In [110]:
# Fix the abnormal records
wages_df.loc[
    (wages_df['year'] == 2013) & (wages_df['noc_code'].isin(['3123', '3221'])), 
    wage_cols
] = wages_df.loc[
    (wages_df['year'] == 2013) & (wages_df['noc_code'].isin(['3123', '3221'])), 
    wage_cols
] / 2000

# Group the DataFrame by year and apply the .describe() method to get summary statistics
wage_summary = wages_df.groupby('year')[wage_cols].describe()

print("Summary Statistics by Year for All Wages (Low, Median, and High):")
print(wage_summary.to_string())

Summary Statistics by Year for All Wages (Low, Median, and High):
     low_wage                                                                     median_wage                                                                     high_wage
        count       mean       std       min      25%     50%      75%        max       count       mean        std    min      25%     50%        75%        max     count       mean        std    min      25%     50%      75%         max
year
2012    520.0  14.429802  4.266255   7.50000  11.0000  14.000  17.0000   33.52000       520.0  24.113750   8.940115  10.00  17.5000  22.680  29.075000   82.27550     520.0  37.487837  16.042033  12.00  27.0350  34.985  43.5900  189.847000
2013    520.0  14.729775  4.330625   9.75000  11.0000  14.000  17.3825   34.00000       520.0  24.541814   9.142421  10.25  18.0000  23.000  29.827500   82.27550     520.0  38.247135  16.542434  13.00  28.0000  35.000  45.0650  189.847000
2014    520.0  15.047976  4.585845  10.00000  11.0000  14.000  18.0000   47.82300       520.0  25.206290  10.033384  10.30  18.0000  23.445  30.228750  108.49000     520.0  39.271190  17.318670  14.25  28.8250  36.000  45.6700  188.230500
2015    520.0  15.519690  4.641671  10.28878  11.5300  15.000  18.0000   47.82000       520.0  25.894273  10.131137  10.30  18.7325  24.290  31.384125  108.49000     520.0  40.249622  17.769394  14.50  29.0000  37.020  47.2175  188.230500
2016    500.0  15.850429  4.678832   4.87050  12.0000  15.000  18.5245   47.82283       500.0  26.557439  10.293346  10.50  19.1825  25.000  32.547500  108.49339     500.0  41.586175  18.006857  14.67  30.0000  38.270  49.0100  188.230500
2017    500.0  16.252625  4.860862  10.85000  12.0000  15.000  19.2300   47.82000       500.0  27.042444  10.480206  10.85  19.8700  25.000  33.347500  108.49000     500.0  42.286107  18.572035  15.00  30.0000  38.585  49.5300  188.230500
2018    498.0  16.706082  5.238904  11.00000  12.6775  15.530  20.0000   65.66000       498.0  27.542573  10.879852  11.40  20.0000  25.635  33.885500  135.65000     498.0  42.329348  17.624409  15.00  30.3150  38.955  50.0000  148.850000
2019    500.0  17.351565  5.535131  11.32000  13.5375  16.000  20.0000   65.66000       500.0  28.410953  12.356201  12.00  20.0000  26.000  34.032500  138.61641     500.0  44.029573  22.133207  15.87  30.9775  40.000  51.2800  277.299230
2020    500.0  18.286562  7.193070  11.45000  14.0000  16.830  21.0000  127.25900       500.0  29.242940  12.941033  13.50  21.0000  26.585  35.000000  153.23800     500.0  44.930155  22.470746  16.00  31.4825  40.405  52.0000  280.017750
2021    500.0  19.029456  7.355771  11.75000  14.9975  17.500  22.0000  127.25900       500.0  30.056875  13.677755  14.00  21.1200  27.470  36.000000  175.29316     500.0  45.860224  22.983886  16.50  32.6275  41.700  52.7825  290.173220
2022    500.0  19.859549  7.337889  13.00000  15.0000  18.275  23.0050  127.25900       500.0  30.900923  13.759344  14.00  22.0000  28.315  37.165000  177.76830     500.0  46.886506  23.197751  17.00  33.0000  42.520  54.9625  278.683195
2023    515.0  21.083063  8.704968  14.00000  16.0000  19.230  24.0200  155.00000       515.0  32.335083  15.640541  14.25  22.5300  29.680  38.460000  189.65950     515.0  49.242320  26.982673  18.00  34.0000  45.000  57.6450  369.694000
2024    514.0  22.044163  9.009617  15.00000  16.7475  20.000  25.0000  155.00000       514.0  33.509305  16.482196  15.00  23.5625  30.290  40.000000  211.53750     514.0  50.748395  28.466432  18.50  34.6050  45.585  58.9700  388.262500

After checking the summary statistics, we can see that the wages are logicaly consistent across all years.

#### **Check the remaining wage comments**

In [111]:
# Check the unique wage comments still present after cleaning
print(wages_df['wage_comment'].unique())

[nan
 'In this occupation, a large number of people are self-employed. For this reason, wages for this occupation are presented at an annual rate to better represent earnings for this occupation.'
 'In this occupation, a large number of people are self-employed. For this reason, wages for this occupation are presented at an annual rate to better repre'
 'In this occupation, a large number of people are self-employed. For this reason, wages for this occupation are presented at an annual rate to better represent earnings for this occupation. \n'
 'Wages for this occupation are presented at an annual rate to better represent earnings for this occupation.']

Since all remaining information in the `wage_comment` column relates solely to the representation of annual wage rates, and we’ve already completed all necessary adjustments and conversions for annual salaries, we can now safely remove both the `wage_comment` and `annual_flag` columns from the DataFrame.

In [112]:
# Drop the wage_comment and annual_flag columns as they are no longer needed
wages_df.drop(columns=['wage_comment', 'annual_flag'], inplace=True)

wages_df.head()

,year,noc_code,noc_title,er_code,er_name,low_wage,median_wage,high_wage
0,2012,0011,Legislators,ER00,Canada,8.17,28.00,49.45
86,2012,0012,Senior Government Managers and Officials,ER00,Canada,20.64,46.15,74.36
172,2012,0013,"Senior Managers - Financial, Communications an...",ER00,Canada,20.29,40.87,75.83
258,2012,0014,"Senior Managers - Health, Education, Social an...",ER00,Canada,19.23,38.46,66.67
344,2012,0015,"Senior Managers - Trade, Broadcasting and Othe...",ER00,Canada,18.90,40.87,72.12

# AI Adoption ([Statistics Canada - Use of Use of advanced or emerging technologies, by industry and enterprise size](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2710036701))

In [113]:
advanced_tech_df = pd.read_csv("../datasets/advanced_tech/Use-of-advanced-tech_Open-Canada.csv")
advanced_tech_df.head()

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Enterprise size,Advanced or emerging technologies,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes",Any advanced or emerging technology use,Percent,239,units,0,v1047697746,1.1.1.17,46.1,A,NaN,NaN,1
1,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes",Advanced technology use,Percent,239,units,0,v1047697730,1.1.1.1,42.8,A,NaN,t,1
2,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes","Material handling, supply chain or logistics t...",Percent,239,units,0,v1047697731,1.1.1.2,12.7,A,NaN,NaN,1
3,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes",Design or information control technologies,Percent,239,units,0,v1047697732,1.1.1.3,17.7,A,NaN,NaN,1
4,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes",Processing or fabrication technologies,Percent,239,units,0,v1047697733,1.1.1.4,12.2,A,NaN,NaN,1

## **Transformation**

In [114]:
# Filter for metrics for all enterprise sizes, as enterprise size is not relevant for our analysis
# Focus on 'Artificial intelligence (AI)' use
ai_adoption_df = advanced_tech_df[
    (advanced_tech_df['Advanced or emerging technologies'] == 'Artificial intelligence (AI)') &
    (advanced_tech_df['Enterprise size'] == 'Total, all enterprise sizes')
].copy()

ai_adoption_df.head()

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Enterprise size,Advanced or emerging technologies,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
12,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697742,1.1.1.13,4.0,A,NaN,NaN,1
80,2017,Canada,2021A000011124,"Agriculture, forestry, fishing and hunting [11]","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697810,1.2.1.13,1.8,A,NaN,NaN,1
148,2017,Canada,2021A000011124,"Mining, quarrying, and oil and gas extraction ...","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697878,1.3.1.13,3.7,A,NaN,NaN,1
216,2017,Canada,2021A000011124,Oil and gas extraction [211],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697946,1.4.1.13,2.1,A,NaN,NaN,1
284,2017,Canada,2021A000011124,Mining and quarrying (except oil and gas) [212],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047698014,1.5.1.13,3.3,A,NaN,NaN,1

#### Major **NAICS** industry sectors

| Code | Sector |
| :--- | :--- |
| 11 | Agriculture, forestry, fishing and hunting |
| 21 | Mining, quarrying, and oil and gas extraction |
| 22 | Utilities |
| 23 | Construction |
| 31-33 | Manufacturing |
| 41 | Wholesale trade |
| 44-45 | Retail trade |
| 48-49 | Transportation and warehousing |
| 51 | Information and cultural industries |
| 52 | Finance and insurance |
| 53 | Real estate and rental and leasing |
| 54 | Professional, scientific and technical services |
| 55 | Management of companies and enterprises |
| 56 | Administrative and support, waste management and remediation services |
| 61 | Educational services |
| 62 | Health care and social assistance |
| 71 | Arts, entertainment and recreation |
| 72 | Accommodation and food services |
| 81 | Other services (except public administration) |
| 91 | Public administration |

To limit the scope of the analysis, we decided to only use the major (2-digit) NAISC industry sectors.  
Instead of ±100 niche industry categories, we will be comparing ±20 macro-sectors, this will help us reduce analytical noise and ensure that our conclusions represent broad trends across the Canadian economy.

In [115]:
# Use regex to extract the 2-digit NAISC sector code contained within [ ] and save it in a separate column
ai_adoption_df['naics_sector'] = ai_adoption_df['North American Industry Classification System (NAICS)'].str.extract(r'\[(.*?)\]')

print('The NAISC sectors present in the dataset:')
print(ai_adoption_df['naics_sector'].unique())

The NAISC sectors present in the dataset:
[nan '11' '21' '211' '212' '213' '22' '23' '31-33' '311' '312' '321' '322'
 '323' '324' '325' '3254' '326' '3261' '326193' '3262' '327' '331' '332'
 '333' '334' '3344' '3345' '335' '336' '3363' '3364' '337' '339' '3391'
 '3399' '41' '411' '412' '413' '414' '4145' '415' '416' '417' '4173' '418'
 '419' '44-45' '48-49' '481' '484' '485' '486' '51' '511' '5111' '5112'
 '512' '515' '517' '518' '519' '523' '5231' '524' '53' '54' '5411' '5412'
 '5413' '5415' '5416' '5417' '5418' '55' '56' '3117']

In [116]:
# These are the major (2-digit) sectors that are present in the dataset
target_major_codes = [ '11', '21', '22', '23', '31-33', '41', '44-45', '48-49', '51', '52', '53', '54', '55', '56' ]

# Create filtering conditions
total_industry_filter = ai_adoption_df['North American Industry Classification System (NAICS)'] == 'Total, all surveyed industries'
major_sector_filter = ai_adoption_df['naics_sector'].isin(target_major_codes)

# Apply filter to keep only major sectors OR the overall total row
ai_adoption_df = ai_adoption_df[major_sector_filter | total_industry_filter]

# Replace missing naics_sector values for the 'Total, all surveyed industries' records with 'TOTAL'
ai_adoption_df['naics_sector'] = ai_adoption_df['naics_sector'].fillna('TOTAL')

print(ai_adoption_df.head().to_string())
print(ai_adoption_df['naics_sector'].unique())

     REF_DATE     GEO           DGUID North American Industry Classification System (NAICS)              Enterprise size Advanced or emerging technologies      UOM  UOM_ID SCALAR_FACTOR  SCALAR_ID       VECTOR COORDINATE  VALUE STATUS  SYMBOL TERMINATED  DECIMALS naics_sector
12       2017  Canada  2021A000011124                        Total, all surveyed industries  Total, all enterprise sizes      Artificial intelligence (AI)  Percent     239         units          0  v1047697742   1.1.1.13    4.0      A     NaN        NaN         1        TOTAL
80       2017  Canada  2021A000011124       Agriculture, forestry, fishing and hunting [11]  Total, all enterprise sizes      Artificial intelligence (AI)  Percent     239         units          0  v1047697810   1.2.1.13    1.8      A     NaN        NaN         1           11
148      2017  Canada  2021A000011124    Mining, quarrying, and oil and gas extraction [21]  Total, all enterprise sizes      Artificial intelligence (AI)  Percent     239         units          0  v1047697878   1.3.1.13    3.7      A     NaN        NaN         1           21
420      2017  Canada  2021A000011124                                        Utilities [22]  Total, all enterprise sizes      Artificial intelligence (AI)  Percent     239         units          0  v1047698150   1.7.1.13    3.4      A     NaN        NaN         1           22
488      2017  Canada  2021A000011124                                     Construction [23]  Total, all enterprise sizes      Artificial intelligence (AI)  Percent     239         units          0  v1047698218   1.8.1.13    0.8      A     NaN        NaN         1           23
['TOTAL' '11' '21' '22' '23' '31-33' '41' '44-45' '48-49' '51' '53' '54'
 '55' '56']

In [117]:
# Rename columns for more clarity
ai_adoption_df.rename(columns={
    'REF_DATE': 'year',
    'North American Industry Classification System (NAICS)': 'naics_name',
    'VALUE': 'ai_adoption_rate',
}, inplace=True)

ai_adoption_df.head()

,year,GEO,DGUID,naics_name,Enterprise size,Advanced or emerging technologies,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,ai_adoption_rate,STATUS,SYMBOL,TERMINATED,DECIMALS,naics_sector
12,2017,Canada,2021A000011124,"Total, all surveyed industries","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697742,1.1.1.13,4.0,A,NaN,NaN,1,TOTAL
80,2017,Canada,2021A000011124,"Agriculture, forestry, fishing and hunting [11]","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697810,1.2.1.13,1.8,A,NaN,NaN,1,11
148,2017,Canada,2021A000011124,"Mining, quarrying, and oil and gas extraction ...","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047697878,1.3.1.13,3.7,A,NaN,NaN,1,21
420,2017,Canada,2021A000011124,Utilities [22],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047698150,1.7.1.13,3.4,A,NaN,NaN,1,22
488,2017,Canada,2021A000011124,Construction [23],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047698218,1.8.1.13,0.8,A,NaN,NaN,1,23

## **Cleaning**

The `Status` column indicates data quality. To ensure the accuracy of our analysis, we decided to investigate the data quality.

#### Symbol Legend (from the dataset's metadata)
| Description | Symbol |
--------------|--------|
| "data quality: excellent" | "A" |
| "data quality: very good" | "B" |
| "data quality: good" | "C" |
| "data quality: acceptable" | "D" |
| "use with caution" | "E" |
| "too unreliable to be published" | "F" |

In [118]:
# Check the data quality of the present records
print(ai_adoption_df['STATUS'].unique())
print(ai_adoption_df['STATUS'].value_counts())

# Inspect the records with quality below 'acceptable'
inspect_df = ai_adoption_df[(ai_adoption_df['STATUS'] == 'E') | (ai_adoption_df['STATUS'] == 'F')]

inspect_df.head(50)

['A' 'B' 'E' 'C' 'F']
STATUS
A    143
B     69
E     20
C      4
F      2
Name: count, dtype: int64

,year,GEO,DGUID,naics_name,Enterprise size,Advanced or emerging technologies,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,ai_adoption_rate,STATUS,SYMBOL,TERMINATED,DECIMALS,naics_sector
6574,2017,Atlantic Region,2021A00011,Utilities [22],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047704304,2.7.1.13,0.0,E,NaN,NaN,1,22
7883,2017,Atlantic Region,2021A00011,Real estate and rental and leasing [53],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705613,2.84.1.13,0.0,E,NaN,NaN,1,53
8053,2017,Atlantic Region,2021A00011,Management of companies and enterprises [55],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705783,2.94.1.13,0.0,E,NaN,NaN,1,55
8070,2017,Atlantic Region,2021A00011,"Administrative and support, waste management a...","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705800,2.95.1.13,0.0,E,NaN,NaN,1,56
8121,2017,Quebec,2021A000224,"Mining, quarrying, and oil and gas extraction ...","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705851,3.3.1.13,0.0,E,NaN,NaN,1,21
20190,2019,Atlantic Region,2021A00011,"Mining, quarrying, and oil and gas extraction ...","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047704236,2.3.1.13,0.0,E,NaN,NaN,1,21
20285,2019,Atlantic Region,2021A00011,Construction [23],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047704321,2.8.1.13,0.0,E,NaN,NaN,1,23
21729,2019,Atlantic Region,2021A00011,Real estate and rental and leasing [53],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705613,2.84.1.13,0.0,E,NaN,NaN,1,53
21919,2019,Atlantic Region,2021A00011,Management of companies and enterprises [55],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705783,2.94.1.13,0.0,E,NaN,NaN,1,55
23781,2019,Ontario,2021A000235,"Agriculture, forestry, fishing and hunting [11]","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047707449,4.2.1.13,0.0,E,NaN,NaN,1,11
35184,2022,Atlantic Region,2021A00011,"Mining, quarrying, and oil and gas extraction ...","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047704236,2.3.1.13,0.0,E,NaN,NaN,1,21
35288,2022,Atlantic Region,2021A00011,Utilities [22],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047704304,2.7.1.13,NaN,F,NaN,NaN,1,22
35314,2022,Atlantic Region,2021A00011,Construction [23],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047704321,2.8.1.13,0.0,E,NaN,NaN,1,23
36952,2022,Atlantic Region,2021A00011,Information and cultural industries [51],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705358,2.69.1.13,42.9,E,NaN,NaN,1,51
37602,2022,Atlantic Region,2021A00011,Management of companies and enterprises [55],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705783,2.94.1.13,0.0,E,NaN,NaN,1,55
37810,2022,Quebec,2021A000224,Utilities [22],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047705919,3.7.1.13,NaN,F,NaN,NaN,1,22
40124,2022,Quebec,2021A000224,Management of companies and enterprises [55],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047707398,3.94.1.13,0.0,E,NaN,NaN,1,55
42724,2022,Rest of Canada,NaN,"Agriculture, forestry, fishing and hunting [11]","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047709064,5.2.1.13,10.4,E,NaN,NaN,1,11
42854,2022,Rest of Canada,NaN,Utilities [22],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1047709149,5.7.1.13,18.1,E,NaN,NaN,1,22
45246,2022,Alberta,2021A000248,"Agriculture, forestry, fishing and hunting [11]","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1586282484,6.2.1.13,0.0,E,NaN,NaN,1,11
45376,2022,Alberta,2021A000248,Utilities [22],"Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1586282554,6.7.1.13,19.9,E,NaN,NaN,1,22
47768,2022,Rest of Canada excluding Alberta,NaN,"Agriculture, forestry, fishing and hunting [11]","Total, all enterprise sizes",Artificial intelligence (AI),Percent,239,units,0,v1586283842,7.2.1.13,14.1,E,NaN,NaN,1,11

Most "use with caution" entries are tied to Atlantic Region.  
The dataset doesn't have the full province-by-province breakdown (that's there regional aggregates like 'Atlantic Region' come from), so to optimize for data quality and to better align with the scope of our datasets, we decided to only keep the values for Canada.

In [119]:
# Filter to only include the national level stats
ai_adoption_df = ai_adoption_df[(ai_adoption_df['GEO'] == 'Canada')]

print(ai_adoption_df['STATUS'].unique())
print(ai_adoption_df['STATUS'].value_counts())

#Check Na values
print(ai_adoption_df.isna().sum())

['A' 'B']
STATUS
A    38
B     4
Name: count, dtype: int64
year                                  0
GEO                                   0
DGUID                                 0
naics_name                            0
Enterprise size                       0
Advanced or emerging technologies     0
UOM                                   0
UOM_ID                                0
SCALAR_FACTOR                         0
SCALAR_ID                             0
VECTOR                                0
COORDINATE                            0
ai_adoption_rate                      0
STATUS                                0
SYMBOL                               42
TERMINATED                           42
DECIMALS                              0
naics_sector                          0
dtype: int64

After narrowing the scope, the `NaN` values and the values with lower data quality are absent.

Now we will remove the columns that are not needed for our analysis to make the dataset more readable and easier to work with.

In [120]:
ai_adoption_df = ai_adoption_df.drop(columns= [
    'Enterprise size', 'Advanced or emerging technologies', 'UOM', #all the same known values
    'DGUID','UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS', # not needed 
    ])

#### Finally, check the AI adoption rate summary statistics.

In [121]:
# Check the summary statistics
ai_adoption_df.groupby('year')['ai_adoption_rate'].describe()

      count      mean       std  min    25%   50%    75%   max
year
2017   14.0  4.392857  4.385372  0.8  2.100  3.10  3.925  16.8
2019   14.0  6.228571  5.947130  0.9  3.150  4.65  6.050  20.9
2022   14.0  7.814286  5.221090  2.2  4.825  5.80  7.600  18.0

AI adoption rates across Canadian NAICS sectors show a steady upward shift from 2017 to 2022, with means and medians rising each year and similar levels of variability, indicating broad but uneven adoption.  
The range widens at the top end (right-skewed), but overall the distribution appears to be consistent, with no clear signs of abnormal values.

In [122]:
# Select final columns to keep
final_columns = ['year', 'GEO', 'naics_name', 'naics_sector', 'ai_adoption_rate']
ai_adoption_df = ai_adoption_df[final_columns]
ai_adoption_df.head()

,year,GEO,naics_name,naics_sector,ai_adoption_rate
12,2017,Canada,"Total, all surveyed industries",TOTAL,4.0
80,2017,Canada,"Agriculture, forestry, fishing and hunting [11]",11,1.8
148,2017,Canada,"Mining, quarrying, and oil and gas extraction ...",21,3.7
420,2017,Canada,Utilities [22],22,3.4
488,2017,Canada,Construction [23],23,0.8

# ---------------------------------------------------------------------------------------------

## **Exports**

In [123]:
wages_df.to_csv("../datasets_cleaned/wages.csv", index=False)
ai_adoption_df.to_csv("../datasets_cleaned/ai_adoption.csv", index=False)